// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package gRPC;

public interface commitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.commitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 largestID = 1;</code>
   */
  long getLargestID();

  /**
   * <code>bool accept = 2;</code>
   */
  boolean getAccept();
}
