// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package gRPC;

public interface getKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.getKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
