// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package gRPC;

public interface prepareMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.prepareMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 ID = 1;</code>
   */
  long getID();
}
