// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package gRPC;

public interface proposeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.proposeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string val = 3;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 3;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();

  /**
   * <code>int32 method = 4;</code>
   */
  int getMethod();
}
