// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package gRPC;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_prepareMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_prepareMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_promise_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_promise_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_proposeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_proposeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_commitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_commitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_getKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_getKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_getResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_getResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\004gRPC\"\034\n\016prepareMessage\022" +
      "\n\n\002ID\030\001 \001(\003\",\n\007promise\022\021\n\tlargestID\030\001 \001(" +
      "\003\022\016\n\006accept\030\002 \001(\010\"F\n\016proposeMessage\022\n\n\002i" +
      "d\030\001 \001(\003\022\013\n\003key\030\002 \001(\t\022\013\n\003val\030\003 \001(\t\022\016\n\006met" +
      "hod\030\004 \001(\005\"3\n\016commitResponse\022\021\n\tlargestID" +
      "\030\001 \001(\003\022\016\n\006accept\030\002 \001(\010\"\025\n\006getKey\022\013\n\003key\030" +
      "\001 \001(\t\"\032\n\013getResponse\022\013\n\003val\030\001 \001(\t2\244\001\n\013Pa" +
      "xosServer\0222\n\013sendPrepare\022\024.gRPC.prepareM" +
      "essage\032\r.gRPC.promise\0229\n\013sendPropose\022\024.g" +
      "RPC.proposeMessage\032\024.gRPC.commitResponse" +
      "\022&\n\003get\022\014.gRPC.getKey\032\021.gRPC.getResponse" +
      "B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gRPC_prepareMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gRPC_prepareMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_prepareMessage_descriptor,
        new java.lang.String[] { "ID", });
    internal_static_gRPC_promise_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gRPC_promise_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_promise_descriptor,
        new java.lang.String[] { "LargestID", "Accept", });
    internal_static_gRPC_proposeMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gRPC_proposeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_proposeMessage_descriptor,
        new java.lang.String[] { "Id", "Key", "Val", "Method", });
    internal_static_gRPC_commitResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gRPC_commitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_commitResponse_descriptor,
        new java.lang.String[] { "LargestID", "Accept", });
    internal_static_gRPC_getKey_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gRPC_getKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_getKey_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_gRPC_getResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_gRPC_getResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_getResponse_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
