// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package gRPC;

public interface putResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.putResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMsg = 1;</code>
   */
  java.lang.String getResponseMsg();
  /**
   * <code>string responseMsg = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMsgBytes();
}
