// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package gRPC;

public interface putRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.putRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string val = 2;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 2;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
